In [1]:
import tensorflow as tf

In [7]:
m = tf.keras.metrics.SparseCategoricalAccuracy()
m.update_state([[2], [1]], [[0.1, 0.6, 0.3], 
                            [0.05, 0.95, 0]])
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [8]:
m.update_state([[1], [1]], [[0.1, 0.6, 0.3], 
                            [0.05, 0.95, 0]])
m.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.75>

In [9]:
m.reset_state()
m.update_state([[1], [1]], [[0.1, 0.6, 0.3], 
                            [0.05, 0.95, 0]])
m.result()                        

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>